const mongoose = require('mongoose');
const SousPrefecture = require('../models/sousPrefectureModel'); // Assurez-vous que le chemin d'accès est correct
const Prefecture = require('../models/prefectureModel'); // Assurez-vous que le chemin d'accès est correct


mongoose.connect('mongodb+srv://xenlior:xenlior@cluster0.aowfv.mongodb.net/api-guinea-geo')
  .then(() => console.log('Connexion à MongoDB réussie !'))
  .catch(() => console.log('Connexion à MongoDB échouée !'));

const sousPrefecturesData = [
  { name: "Arfamoussaya", prefecture: "Dabola" },
  { name: "Banko", prefecture: "Dabola" },
  { name: "Bissikrima", prefecture: "Dabola" },
  { name: "Dabola-Centre (urban)", prefecture: "Dabola" },
  { name: "Dogomet", prefecture: "Dabola" },
  { name: "Kankama", prefecture: "Dabola" },
  { name: "Kindoyé", prefecture: "Dabola" },
  { name: "Konendou", prefecture: "Dabola" },
  { name: "N'Déma", prefecture: "Dabola" },

  { name: "Banora", prefecture: "Dinguiraye" },
  { name: "Dialakoro", prefecture: "Dinguiraye" },
  { name: "Diatifèrè", prefecture: "Dinguiraye" },
  { name: "Dinguiraye-Centre (urban)", prefecture: "Dinguiraye" },
  { name: "Gagnakaly", prefecture: "Dinguiraye" },
  { name: "Kalinko", prefecture: "Dinguiraye" },
  { name: "Lansanaya", prefecture: "Dinguiraye" },
  { name: "Sélouma", prefecture: "Dinguiraye" },

  { name: "Banian", prefecture: "Faranah" },
{ name: "Beindou", prefecture: "Faranah" },
{ name: "Faranah-Centre (urban)", prefecture: "Faranah" },
{ name: "Gnaléah", prefecture: "Faranah" },
{ name: "Hérémakonon", prefecture: "Faranah" },
{ name: "Kobikoro", prefecture: "Faranah" },
{ name: "Marela", prefecture: "Faranah" },
{ name: "Passaya", prefecture: "Faranah" },
{ name: "Sandéniyah", prefecture: "Faranah" },
{ name: "Songoyah", prefecture: "Faranah" },
{ name: "Tiro", prefecture: "Faranah" },
{ name: "Tindo", prefecture: "Faranah" },

{ name: "Albadariah", prefecture: "Kissidougou" },
{ name: "Banama", prefecture: "Kissidougou" },
{ name: "Bardou", prefecture: "Kissidougou" },
{ name: "Beindou", prefecture: "Kissidougou" },
{ name: "Fermessadou-Pombo", prefecture: "Kissidougou" },
{ name: "Firawa-Yomadou", prefecture: "Kissidougou" },
{ name: "Gbangbadou", prefecture: "Kissidougou" },
{ name: "Kissidougou-Centre (urban)", prefecture: "Kissidougou" },
{ name: "Koundiatou", prefecture: "Kissidougou" },
{ name: "Manfran", prefecture: "Kissidougou" },
{ name: "Sangardo", prefecture: "Kissidougou" },
{ name: "Yendé-Millimou", prefecture: "Kissidougou" },
{ name: "Yombiro", prefecture: "Kissidougou" },

{ name: "Balandougou", prefecture: "Kankan" },
{ name: "Baté-Nafadji", prefecture: "Kankan" },
{ name: "Boula", prefecture: "Kankan" },
{ name: "Gbérédou-Baranama", prefecture: "Kankan" },
{ name: "Kanfamoriya", prefecture: "Kankan" },
{ name: "Kankan-Centre (urban)", prefecture: "Kankan" },
{ name: "Koumba", prefecture: "Kankan" },
{ name: "Mamouroudou", prefecture: "Kankan" },
{ name: "Misamana", prefecture: "Kankan" },
{ name: "Moribaya", prefecture: "Kankan" },
{ name: "Sabadou-Baranama", prefecture: "Kankan" },
{ name: "Tinti-Oulen", prefecture: "Kankan" },
{ name: "Tokounou", prefecture: "Kankan" },

{ name: "Banankoro", prefecture: "Kérouané" },
{ name: "Damaro", prefecture: "Kérouané" },
{ name: "Kérouané-Centre (urban)", prefecture: "Kérouané" },
{ name: "Komodou", prefecture: "Kérouané" },
{ name: "Kounsankoro", prefecture: "Kérouané" },
{ name: "Linko", prefecture: "Kérouané" },
{ name: "Sibiribaro", prefecture: "Kérouané" },
{ name: "Soromayah", prefecture: "Kérouané" },

{ name: "Babila", prefecture: "Kouroussa" },
{ name: "Balato", prefecture: "Kouroussa" },
{ name: "Banfèlè", prefecture: "Kouroussa" },
{ name: "Baro", prefecture: "Kouroussa" },
{ name: "Cisséla", prefecture: "Kouroussa" },
{ name: "Douako", prefecture: "Kouroussa" },
{ name: "Doura", prefecture: "Kouroussa" },
{ name: "Kiniéro", prefecture: "Kouroussa" },
{ name: "Koumana", prefecture: "Kouroussa" },
{ name: "Komola-Koura", prefecture: "Kouroussa" },
{ name: "Kouroussa-Centre (urban)", prefecture: "Kouroussa" },
{ name: "Sanguiana", prefecture: "Kouroussa" },

{ name: "Balandougouba", prefecture: "Mandiana" },
{ name: "Dialakoro", prefecture: "Mandiana" },
{ name: "Faralako", prefecture: "Mandiana" },
{ name: "Kantoumania", prefecture: "Mandiana" },
{ name: "Kiniéran", prefecture: "Mandiana" },
{ name: "Koudianakoro", prefecture: "Mandiana" },
{ name: "Koundian", prefecture: "Mandiana" },
{ name: "Mandiana-Centre (urban)", prefecture: "Mandiana" },
{ name: "Morodou", prefecture: "Mandiana" },
{ name: "Niantanina", prefecture: "Mandiana" },
{ name: "Saladou", prefecture: "Mandiana" },
{ name: "Sansando", prefecture: "Mandiana" },

{ name: "Bankon", prefecture: "Siguiri" },
{ name: "Doko", prefecture: "Siguiri" },
{ name: "Franwalia", prefecture: "Siguiri" },
{ name: "Kiniébakora", prefecture: "Siguiri" },
{ name: "Kintinian", prefecture: "Siguiri" },
{ name: "Maléah", prefecture: "Siguiri" },
{ name: "Naboun", prefecture: "Siguiri" },
{ name: "Niagassola", prefecture: "Siguiri" },
{ name: "Niandankoro", prefecture: "Siguiri" },

{ name: "Beyla-Centre (urban)", prefecture: "Beyla" },
{ name: "Boola", prefecture: "Beyla" },
{ name: "Diara-Guéréla", prefecture: "Beyla" },
{ name: "Diassodou", prefecture: "Beyla" },
{ name: "Fouala", prefecture: "Beyla" },
{ name: "Gbackédou", prefecture: "Beyla" },
{ name: "Gbéssoba", prefecture: "Beyla" },
{ name: "Karala", prefecture: "Beyla" },
{ name: "Koumandou", prefecture: "Beyla" },
{ name: "Mousadou", prefecture: "Beyla" },
{ name: "Nionsomoridou", prefecture: "Beyla" },
{ name: "Samana", prefecture: "Beyla" },
{ name: "Sinko", prefecture: "Beyla" },
{ name: "Sokourala", prefecture: "Beyla" },

{ name: "Bolodou", prefecture: "Guéckédou" },
{ name: "Fangamadou", prefecture: "Guéckédou" },
{ name: "Guéckédou-Centre (urban)", prefecture: "Guéckédou" },
{ name: "Guéndembou", prefecture: "Guéckédou" },
{ name: "Kassadou", prefecture: "Guéckédou" },
{ name: "Koundou", prefecture: "Guéckédou" },
{ name: "Nongoa", prefecture: "Guéckédou" },
{ name: "Ouéndé-Kénéma", prefecture: "Guéckédou" },
{ name: "Tékoulo", prefecture: "Guéckédou" },
{ name: "Termessadou-Djibo", prefecture: "Guéckédou" },

{ name: "Bossou", prefecture: "Lola" },
{ name: "Foumbadou", prefecture: "Lola" },
{ name: "Gama", prefecture: "Lola" },
{ name: "Guéassou", prefecture: "Lola" },
{ name: "Kokota", prefecture: "Lola" },
{ name: "Laine", prefecture: "Lola" },
{ name: "Lola-Centre (urban)", prefecture: "Lola" },
{ name: "N'Zoo", prefecture: "Lola" },
{ name: "Tounkarata", prefecture: "Lola" },

{ name: "Balizia", prefecture: "Macenta" },
{ name: "Binikala", prefecture: "Macenta" },
{ name: "Bofossou", prefecture: "Macenta" },
{ name: "Daro", prefecture: "Macenta" },
{ name: "Fassankoni", prefecture: "Macenta" },
{ name: "Kouankan", prefecture: "Macenta" },
{ name: "Koyama", prefecture: "Macenta" },
{ name: "Macenta-Centre (urban)", prefecture: "Macenta" },
{ name: "N'Zébéla", prefecture: "Macenta" },
{ name: "Ourémaï", prefecture: "Macenta" },
{ name: "Panziazou", prefecture: "Macenta" },
{ name: "Sengbédou", prefecture: "Macenta" },
{ name: "Sérédou", prefecture: "Macenta" },
{ name: "Vasérédou", prefecture: "Macenta" },
{ name: "Watanka", prefecture: "Macenta" },

{ name: "Bounouma", prefecture: "Nzérékoré" },
{ name: "Gouécké", prefecture: "Nzérékoré" },
{ name: "Kobéla", prefecture: "Nzérékoré" },
{ name: "Koropara", prefecture: "Nzérékoré" },
{ name: "Koulé", prefecture: "Nzérékoré" },
{ name: "N'Zérékoré-Centre (urban)", prefecture: "Nzérékoré" },
{ name: "Palé", prefecture: "Nzérékoré" },
{ name: "Samoé", prefecture: "Nzérékoré" },
{ name: "Soulouta", prefecture: "Nzérékoré" },
{ name: "Womey", prefecture: "Nzérékoré" },
{ name: "Yalenzou", prefecture: "Nzérékoré" },

{ name: "Banié", prefecture: "Yomou" },
{ name: "Bheeta", prefecture: "Yomou" },
{ name: "Bignamou", prefecture: "Yomou" },
{ name: "Bowé", prefecture: "Yomou" },
{ name: "Diécké", prefecture: "Yomou" },
{ name: "Péla", prefecture: "Yomou" },
{ name: "Yomou-Centre (urban)", prefecture: "Yomou" },

{ name: "Boffa-Centre (urban)", prefecture: "Boffa" },
{ name: "Colia", prefecture: "Boffa" },
{ name: "Douprou", prefecture: "Boffa" },
{ name: "Koba-Tatema", prefecture: "Boffa" },
{ name: "Lisso", prefecture: "Boffa" },
{ name: "Mankountan", prefecture: "Boffa" },
{ name: "Tamita", prefecture: "Boffa" },
{ name: "Tougnifily", prefecture: "Boffa" },

{ name: "Bintimodia", prefecture: "Boké" },
{ name: "Boké-Centre (urban)", prefecture: "Boké" },
{ name: "Dabiss", prefecture: "Boké" },
{ name: "Kamsar (urban)", prefecture: "Boké" },
{ name: "Kanfarandé", prefecture: "Boké" },
{ name: "Kolaboui", prefecture: "Boké" },
{ name: "Malapouyah", prefecture: "Boké" },
{ name: "Sangarédi (urban)", prefecture: "Boké" },
{ name: "Sansalé", prefecture: "Boké" },
{ name: "Tanènè", prefecture: "Boké" },

{ name: "Banguinet", prefecture: "Fria" },
{ name: "Banguingny", prefecture: "Fria" },
{ name: "Fria-Centre (urban)", prefecture: "Fria" },
{ name: "Tormelin", prefecture: "Fria" },

{ name: "Foulamory", prefecture: "Gaoual" },
{ name: "Gaoual-Centre (urban)", prefecture: "Gaoual" },
{ name: "Kakony", prefecture: "Gaoual" },
{ name: "Koumbia", prefecture: "Gaoual" },
{ name: "Kounsitel", prefecture: "Gaoual" },
{ name: "Malanta", prefecture: "Gaoual" },
{ name: "Touba", prefecture: "Gaoual" },
{ name: "Wendou M'Bour", prefecture: "Gaoual" },

{ name: "Guingan", prefecture: "Koundara" },
{ name: "Kamaby", prefecture: "Koundara" },
{ name: "Koundara-Centre (urban)", prefecture: "Koundara" },
{ name: "Sambaïlo", prefecture: "Koundara" },
{ name: "Saréboïdo", prefecture: "Koundara" },
{ name: "Termessé", prefecture: "Koundara" },
{ name: "Youkounkoun", prefecture: "Koundara" },

{ name: "Coyah-Centre (urban)", prefecture: "Coyah" },
{ name: "Kouriah", prefecture: "Coyah" },
{ name: "Manéah", prefecture: "Coyah" },
{ name: "Wonkifong", prefecture: "Coyah" },

{ name: "Badi", prefecture: "Dubréka" },
{ name: "Dubréka-Centre (urban)", prefecture: "Dubréka" },
{ name: "Faléssadé", prefecture: "Dubréka" },
{ name: "Khorira", prefecture: "Dubréka" },
{ name: "Ouassou", prefecture: "Dubréka" },
{ name: "Tanènè", prefecture: "Dubréka" },
{ name: "Tondon", prefecture: "Dubréka" },

{ name: "Alassoyah", prefecture: "Forécariah" },
{ name: "Benty", prefecture: "Forécariah" },
{ name: "Farmoriyah", prefecture: "Forécariah" },
{ name: "Forécariah-Centre (urban)", prefecture: "Forécariah" },
{ name: "Kaback", prefecture: "Forécariah" },
{ name: "Kakossa", prefecture: "Forécariah" },
{ name: "Kallia", prefecture: "Forécariah" },
{ name: "Maférinyah", prefecture: "Forécariah" },
{ name: "Moussayah", prefecture: "Forécariah" },
{ name: "Sikhourou", prefecture: "Forécariah" },

{ name: "Bangouya", prefecture: "Kindia" },
{ name: "Damankaniah", prefecture: "Kindia" },
{ name: "Friguiagbé", prefecture: "Kindia" },
{ name: "Kindia-Centre (urban)", prefecture: "Kindia" },
{ name: "Kolenté", prefecture: "Kindia" },
{ name: "Madina-Oula", prefecture: "Kindia" },
{ name: "Mambia", prefecture: "Kindia" },
{ name: "Molota", prefecture: "Kindia" },
{ name: "Samaya", prefecture: "Kindia" },
{ name: "Souguéta", prefecture: "Kindia" },

{ name: "Bourouwal", prefecture: "Télimélé" },
{ name: "Daramagnaki", prefecture: "Télimélé" },
{ name: "Gougoudjé", prefecture: "Télimélé" },
{ name: "Koba", prefecture: "Télimélé" },
{ name: "Kollet", prefecture: "Télimélé" },
{ name: "Konsotami", prefecture: "Télimélé" },
{ name: "Missira", prefecture: "Télimélé" },
{ name: "Santou", prefecture: "Télimélé" },
{ name: "Sarékali", prefecture: "Télimélé" },
{ name: "Sinta", prefecture: "Télimélé" },
{ name: "Sogolon", prefecture: "Télimélé" },
{ name: "Tarihoye", prefecture: "Télimélé" },
{ name: "Télimélé-Centre (urban)", prefecture: "Télimélé" },
{ name: "Thionthian", prefecture: "Télimélé" },

{ name: "Fafaya", prefecture: "Koubia" },
{ name: "Gadha-Woundou", prefecture: "Koubia" },
{ name: "Koubia-Centre (urban)", prefecture: "Koubia" },
{ name: "Matakaou", prefecture: "Koubia" },
{ name: "Missira", prefecture: "Koubia" },
{ name: "Pilimini", prefecture: "Koubia" },

{ name: "Dalein", prefecture: "Labé" },
{ name: "Daralabe", prefecture: "Labé" },
{ name: "Diari", prefecture: "Labé" },
{ name: "Dionfo", prefecture: "Labé" },
{ name: "Garambé", prefecture: "Labé" },
{ name: "Hafia", prefecture: "Labé" },
{ name: "Kaalan", prefecture: "Labé" },
{ name: "Kouramandji", prefecture: "Labé" },
{ name: "Labé-Centre (urban)", prefecture: "Labé" },
{ name: "Noussy", prefecture: "Labé" },
{ name: "Popodara", prefecture: "Labé" },
{ name: "Sannoun", prefecture: "Labé" },
{ name: "Tountouroun", prefecture: "Labé" },

{ name: "Balaya", prefecture: "Lélouma" },
{ name: "Diountou", prefecture: "Lélouma" },
{ name: "Hérico", prefecture: "Lélouma" },
{ name: "Korbè", prefecture: "Lélouma" },
{ name: "Lafou", prefecture: "Lélouma" },
{ name: "Lélouma-Centre (urban)", prefecture: "Lélouma" },
{ name: "Linsan", prefecture: "Lélouma" },
{ name: "Manda", prefecture: "Lélouma" },
{ name: "Parawol", prefecture: "Lélouma" },
{ name: "Sagalé", prefecture: "Lélouma" },
{ name: "Tyanguel-Bori", prefecture: "Lélouma" },

{ name: "Balaki", prefecture: "Mali" },
{ name: "Donghol-Sigon", prefecture: "Mali" },
{ name: "Dougountouny", prefecture: "Mali" },
{ name: "Fougou", prefecture: "Mali" },
{ name: "Gayah", prefecture: "Mali" },
{ name: "Hidayatou", prefecture: "Mali" },
{ name: "Lébékére", prefecture: "Mali" },
{ name: "Madina-Wora", prefecture: "Mali" },
{ name: "Mali-Centre (urban)", prefecture: "Mali" },
{ name: "Madina-Salambandé", prefecture: "Mali" },
{ name: "Téliré", prefecture: "Mali" },
{ name: "Touba", prefecture: "Mali" },
{ name: "Yimbéring", prefecture: "Mali" },

{ name: "Fatako", prefecture: "Tougué" },
{ name: "Fello-Koundoua", prefecture: "Tougué" },
{ name: "Kansangui", prefecture: "Tougué" },
{ name: "Kolangui", prefecture: "Tougué" },
{ name: "Kollet", prefecture: "Tougué" },
{ name: "Konah", prefecture: "Tougué" },
{ name: "Kouratongo", prefecture: "Tougué" },
{ name: "Koyïn", prefecture: "Tougué" },
{ name: "Tangali", prefecture: "Tougué" },
{ name: "Tougué-Centre (urban)", prefecture: "Tougué" },

{ name: "Bodié", prefecture: "Dalaba" },
{ name: "Dalaba-Centre (urban)", prefecture: "Dalaba" },
{ name: "Ditinn", prefecture: "Dalaba" },
{ name: "Kaala", prefecture: "Dalaba" },
{ name: "Kankalabé", prefecture: "Dalaba" },
{ name: "Kébali", prefecture: "Dalaba" },
{ name: "Koba", prefecture: "Dalaba" },
{ name: "Mafara", prefecture: "Dalaba" },
{ name: "Mitty", prefecture: "Dalaba" },
{ name: "Mombéyah", prefecture: "Dalaba" },

{ name: "Bouliwel", prefecture: "Mamou" },
{ name: "Dounet", prefecture: "Mamou" },
{ name: "Gongorèt", prefecture: "Mamou" },
{ name: "Kégnéko", prefecture: "Mamou" },
{ name: "Konkouré", prefecture: "Mamou" },
{ name: "Mamou-Centre (urban)", prefecture: "Mamou" },
{ name: "Nyagara", prefecture: "Mamou" },
{ name: "Ouré-Kaba", prefecture: "Mamou" },
{ name: "Porédaka", prefecture: "Mamou" },
{ name: "Saramoussayah", prefecture: "Mamou" },
{ name: "Soyah", prefecture: "Mamou" },
{ name: "Téguéréya", prefecture: "Mamou" },
{ name: "Timbo", prefecture: "Mamou" },
{ name: "Tolo", prefecture: "Mamou" },

{ name: "Bantignel", prefecture: "Pita" },
{ name: "Bourouwal-Tappé", prefecture: "Pita" },
{ name: "Dongol-Touma", prefecture: "Pita" },
{ name: "Gongorè", prefecture: "Pita" },
{ name: "Ley-Miro", prefecture: "Pita" },
{ name: "Maci", prefecture: "Pita" },
{ name: "Ninguélandé", prefecture: "Pita" },
{ name: "Pita-Centre (urban)", prefecture: "Pita" },
{ name: "Sangaréyah", prefecture: "Pita" },
{ name: "Sintali", prefecture: "Pita" },
{ name: "Timbi-Madina", prefecture: "Pita" },
{ name: "Timbi-Touny", prefecture: "Pita" }
];

async function clearSousPrefectureData() {
  try {
    await SousPrefecture.deleteMany({});
    console.log('Données de SousPrefecture supprimées');
    // Insertion de données ou autres opérations ici
  } catch (error) {
    console.error('Erreur lors de la suppression des données de SousPrefecture:', error);
  }
}

async function insertSousPrefectures() {
  try {
    for (let data of sousPrefecturesData) {
      const prefecture = await Prefecture.findOne({ name: data.prefecture }); // Trouver la préfecture par nom
      if (prefecture) {
        let newSousPrefecture = new SousPrefecture({ ...data, prefecture: prefecture._id });
        await newSousPrefecture.save();
      } else {
        console.log(`Préfecture ${data.prefecture} non trouvée`);
      }
    }
    console.log('Sous-préfectures insérées avec succès !');
  } catch (error) {
    console.error('Erreur lors de l\'insertion des sous-préfectures :', error);
  } finally {
    mongoose.connection.close();
  }
}
clearSousPrefectureData();
insertSousPrefectures();